/*
 * Copyright (C) 2016-2022 Melexis N.V.
 *
 * Software Platform
 *
 * This firmware example is written to measure periodically:
 * the battery voltage, temperature and pressure with the next RF reporting.
 * The default reports' periodicity is about 4s (specified by constant DEFAULT_STT).
 * The reporting includes 4 identical RFTx telegrams (specified by constant FRAMES_per_REPORT)
 * transmitted with random delays.
 * Between the RFTx telegrams and between the states when the MCU is active
 * the part stays in the (deep)sleep mode to save energy.
 *
 * The RFTx central carrier frequency is set to 433,92 MHz.
 * FSK modulation is done approximately with +/-35 kHz deviation.
 * Data rate = 9600 bps for the used Manchester encoding.
 * There is a structure of the report telegram:
 * Preamble + Sync_word + ID + Pressure + Temperature + Acceleration + Battery_Voltage + CRC8
 * where:
 * "Preamble" ->  1 byte with value 0x00 Manchester coded
 * "Sync_word" -> 1 byte with value 0x01 Manchester coded
 * "ID" -> 4 bytes of the unique chip ID of the device
 * "Pressure" -> 1 byte with pressure data that can be converted to the [kPa] scale by formulas:
 * if "Pressure" = 0:    measurement error happened
 * if "Pressure" = 1:    Pressure_kPa < 100 kPa (underflow)
 * if "Pressure" = 2:    Pressure_kPa = 100 kPa
 * if "Pressure" = 0xFE: Pressure_kPa = 730 kPa
 * if "Pressure" = 0xFF: Pressure_kPa > 730 kPa (overflow)
 * else Pressure_kPa [kPa] = 100 + 2.5 * ("Pressure" - 2)
 * "Temperature" -> 1 byte with temperature data that can be converted to the [degC] scale by formulas:
 * if "Temperature" = 0:    measurement error happened
 * if "Temperature" = 1:    Temperature_degC < -40 degC
 * if "Temperature" = 0xF8: Temperature_degC > 125 degC
 * else Temperature_degC [degC] = "Temperature" - 52
 * "Acceleration" -> 2 bytes with acceleration data: "Acc_H" (first) and "Acc_L" (second):
 * acceleration value = "Acc_H" * 256 + "Acc_L"
 * If RAW_ADC_WITH_HW_FILTERING is defined, the acceleration value is expressed in LSB of ADC,
 * otherwise the acceleration value is expressed in "g/10"
 * "Battery_Voltage" -> 1 byte with battery voltage data that can be converted to the [Volt] scale by formulas:
 * if "Battery_Voltage" = 0:    Battery_Voltage_V < 1.5 V
 * if "Battery_Voltage" = 0xFF: Battery_Voltage_V > 4.0 V
 * else Battery_Voltage_V [V] = ("Battery_Voltage" + 150.)/100.
 * "CRC8" -> 1 byte that is generated by the part's HW according to the Baicheva's
 *  8-bit polynomial = x^8 + x^5 + x^3 + x^2 + x + 1 (0x12F) with preload value 0xAA
 *
 * The RFTx reports' periodicity can be configured by means of the LF commands.
 * There is a structure of the LF commands: Synchronization_field + Wakeup_ID + Data
 * "Wakeup_ID" field includes 2 bytes: 0x8F (first) and 0x61 (second)
 * "Data" field includes 4 bytes: 0x01 0x02 0x03 0x04 (fixed values just as an example)
 * and the last byte XX is a byte with a command code that is used either to generate a SW reset
 * or to redefine the report periodicity. This is a line of acceptable XX bytes:
 * 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF
 * or 0x5A (defined via RESET_CODE)
 * If the Command Code equals to 0x5A, the SW reset will be generated in 8 seconds
 * that is specified by values RESET_DELAY. This feature can be useful
 * to provoke a cold bootstrap and by this way to pass execution to the LF boot loader.
 * Otherwise, the nibble of the Command Code specifies a report periodicity expressed in seconds.
 * For example, the value 0x77 will set 7 seconds for the report periodicity.
 * Zero value disables measurements and reports until the next LF command
 * with non-zero nibbles is received.
 */

/* Define RAW_ADC_WITH_HW_FILTERING to measure raw acceleration with antialiasing HW filter */
#if 0
#define RAW_ADC_WITH_HW_FILTERING
#endif

/* Define STORAGE_MODE_AT_ATMOSPHERIC_PRESSURE to prevent RFTx reports at atmospheric pressure */
#if 0
#define STORAGE_MODE_AT_ATMOSPHERIC_PRESSURE
#endif

#include <sensorlib.h>
#include <platformlib.h>

/* Wake up timer interval:
(WUPTMR_MANT + 1) milli-seconds for WUPTMR_EXP = 0
(WUPTMR_MANT + 257) * 2^(WUPTMR_EXP-1) milli-seconds for WUPTMR_EXP > 0
(WUPTMR_EXP maximized to 12) */
#define MANT_100ms  (100-1)
#define EXP_100ms   0
#define MANT_250ms  (250-1)
#define EXP_250ms   0
#define MANT_500ms  (MANT_1s)
#define EXP_500ms   (EXP_1s - 1)
#define MANT_1s     243
#define EXP_1s      2
#define MANT_2s     (MANT_500ms)
#define EXP_2s      (EXP_1s + 1)
#define MANT_3s     118
#define EXP_3s      4
#define MANT_4s     (MANT_1s)
#define EXP_4s      (EXP_1s + 2)
#define MANT_5s     55
#define EXP_5s      5
#define MANT_6s     (MANT_3s)
#define EXP_6s      (EXP_3s + 1)
#define MANT_7s     180
#define EXP_7s      5
#define MANT_8s     (MANT_1s)
#define EXP_8s      (EXP_1s + 3)
#define MANT_9s     24
#define EXP_9s      6
#define MANT_10s    (MANT_5s)
#define EXP_10s     (EXP_5s + 1)
#define MANT_11s    87
#define EXP_11s     6
#define MANT_12s    (MANT_3s)
#define EXP_12s     (EXP_3s + 2)
#define MANT_13s    149
#define EXP_13s     6
#define MANT_14s    (MANT_7s)
#define EXP_14s     (EXP_7s + 1)
#define MANT_15s    212
#define EXP_15s     6
#define MANT_16s    (MANT_1s)
#define EXP_16s     (EXP_1s + 4)
#define MANT_20s    (MANT_5s)
#define EXP_20s     (EXP_5s + 2)
#define MANT_30s    (MANT_15s)
#define EXP_30s     (EXP_15s + 1)
#define MANT_60s    (MANT_15s)
#define EXP_60s     (EXP_15s + 2)
#define MANT_max    0xFF                    /* Maximal possible period (default value) */
#define EXP_max     0x0C

#define TRANSFER_DELAY          (WT_PERIOD_250_MS)
#define RESET_DELAY             (WT_PERIOD_8_S)

#define STORAGE_MODE_PRESSURE   (130u)      /* kPa */
#define STORAGE_MODE_THRESHOLD  ((STORAGE_MODE_PRESSURE - 100u) * 10u / 25u)

#define RFTx_MIN_RANDOM_DELAY   (50u)       /* Fixed minimal random delay in msec (must be < 128) */

#define FRAMES_per_REPORT       (4u)        /* This value should not be zero! */

#define DUMMY_CODE              (0x00u)

#define NO_RESET                (0x00u)
#define RESET_CODE              (0x5Au)     /* This value should include different nibbles and should not be equal to NO_RESET */

/* Maximal temperature deviation in [degC] that doesn't require RFTx calibration */
#define RFTX_TEMPERATURE_THRESHOLD  (10)
#define REQUEST                     (0u)
#define NO_REQUEST                  (1u)

STATIC INLINE void InitRFTx(void);
STATIC INLINE void InitLFRx(void);
STATIC INLINE void InitIOports(void);
STATIC void WakeupTimer_Random_Init(void);
STATIC INLINE void InitRandomGenerator(void);
STATIC void Measure_PTVA(void);
STATIC INLINE void Process_LF_Message(void);

/* ----------------------------------------------------------------------------
 * NVRAM and Scratchpad parameters
 */

STATIC uint16_t SP_MEM random_base;         /* Two values used to calculate a random delay */
STATIC uint16_t SP_MEM rand_lfsr;
STATIC uint8_t  SP_MEM RFTx_Frame_Counter;
STATIC uint8_t  SP_MEM previous_temperature;
STATIC uint8_t  SP_MEM STT_id;              /* To store STT duration that can be set by LF command */
STATIC uint8_t  SP_MEM reset_cmd;           /* To store a reset command while a big delay before */

STATIC const uint8_t    WUT_MANT[16] = {
MANT_max, MANT_1s, MANT_2s,  MANT_3s,  MANT_4s,  MANT_5s,  MANT_6s,  MANT_7s,
MANT_8s, MANT_9s, MANT_10s, MANT_11s, MANT_12s, MANT_13s, MANT_14s, MANT_15s };
STATIC const uint8_t    WUT_EXP[16]  = {
EXP_max, EXP_1s, EXP_2s, EXP_3s, EXP_4s, EXP_5s, EXP_6s, EXP_7s,
EXP_8s, EXP_9s, EXP_10s, EXP_11s, EXP_12s, EXP_13s, EXP_14s, EXP_15s };

#define DEFAULT_STT    (4u)

#define TX_SIZE        (9u)                 /* Fixed payload size of the RF report */

/* Between the frames of any message the part is in the Sleep mode with retained RAM content
 * Thus, to optimize the Scratchpad memory use the RFTx payload data can be stored in RAM */
STATIC uint8_t Tx_buf[TX_SIZE];

STATIC uint8_t RFTx_Calibration;            /* defines a need of the RFTx calibration */

/* ----------------------------------------------------------------------------
 * MAIN
 */
int main (void)
{
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
    if (Sys_IsColdBoot())
    {   /* Cold boot: */
        InitIOports();
        InitRFTx();
        InitLFRx();
        InitRandomGenerator();
        STT_id = DEFAULT_STT;
        /* Define reporting mode depending on the STT_id value: */
        if (DEFAULT_STT == 0u)
        {   /* Initial mode is specified without reports */
            WakeupTimer_Init(WUT_MANT[STT_id], WUT_EXP[STT_id]);
            RFTx_Frame_Counter = 0u;        /* No reports for zero STT_id */
        }
        else
        {
            Measure_PTVA();
            if (FRAMES_per_REPORT == 1u)
            {
                WakeupTimer_Init(WUT_MANT[STT_id], WUT_EXP[STT_id]);
            }
            else
            {
                WakeupTimer_Random_Init();
            }
            RFTx_Frame_Counter = FRAMES_per_REPORT;
        }
        previous_temperature = 0u;
        RFTx_Calibration = REQUEST; /* First time RFTx calibration is strictly needed */
        reset_cmd = NO_RESET;
    }
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
    else if (reset_cmd != NO_RESET)
    {
	    Sys_ResetCpu();
    }
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
    else if (Itc_IsPending(ITC_LFRX_DONE))
    {   /* Part was woken up by the end of LFRx */
        Process_LF_Message();
        Sys_DeepSleepWith(LF_RECEIVE);
    }
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
    else if (STT_id == 0u)
    {   /* This branch prevents measurements and RF reporting if LF command set zero value for STT_id */
        RFTx_Frame_Counter = 0u;    /* No RFTx activity */
        WakeupTimer_IntClear();     /* Just clear WUPTMR_FLAG and corresponding PEND flag */
    }
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
    else if (Itc_IsPending(ITC_WUPTMR))
    {   /* Part was woken up by the Wake-Up Timer supporting either STT, or a delay between RF frames */
        if (RFTx_Frame_Counter == 0u)
        {   /* It is a wake-up after a main delay (STT) -> Measure_PTVA */
            Measure_PTVA();
            if (FRAMES_per_REPORT == 1u)
            {
                WakeupTimer_Init(WUT_MANT[STT_id], WUT_EXP[STT_id]);
            }
            else
            {
                WakeupTimer_Random_Init();
            }
            RFTx_Frame_Counter = FRAMES_per_REPORT;
        }
        /* Else: wake-ups happened after a random delay to generate RFTx frame of the message */
        /* Note: it's presumed that the WUT period is always longer than RFTx frame duration */
        else if (RFTx_Frame_Counter == 1u)
        {   /* The last frame of the message has to be sent -> the main delay should be set */
            WakeupTimer_Init(WUT_MANT[STT_id], WUT_EXP[STT_id]);
            /* RFTx calibration can be needed only before the first frame of the RF report */
            RFTx_Calibration = NO_REQUEST;  /* No RFTx calibration */
        }
        else
        {   /* Not the last frame of the message has to be sent -> the random delay should be set */
            WakeupTimer_Random_Init();
            /* RFTx calibration can be needed only before the first frame of the RF report */
            RFTx_Calibration = NO_REQUEST;  /* No RFTx calibration */
        }
    }
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
    else
    {   /* FAULT branch, since other wake-ups (from Diagn interface, termo-sensor, GPIOs) are not expected */
	    Sys_ResetCpu();
    }
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
    /* Go to stanby mode with or without RFTx & LFRx: */
    LfRx_FifoFlush();
    if (RFTx_Frame_Counter == 0u)
    {   /* RFTx is not requested */
        Sys_DeepSleepWith(LF_RECEIVE);
    }
    else
    {   /* RFTx is requested */
        #if defined (STORAGE_MODE_AT_ATMOSPHERIC_PRESSURE)
        if (Tx_buf[4] < STORAGE_MODE_THRESHOLD)
        {   /* Finish by Deep Sleep if pressure is below threshold */
            RFTx_Frame_Counter = 0u;
            WakeupTimer_Init(WUT_MANT[STT_id], WUT_EXP[STT_id]); /* Periodicity of measurements */
            Sys_DeepSleepWith(LF_RECEIVE);
        }
        else
        { /* Continue with RFTx */ }
        #endif /* STORAGE_MODE_AT_ATMOSPHERIC_PRESSURE */

        RFTx_Frame_Counter -= 1u;       /* Decrement the frame counter */
        RfTx_FifoFlush();
        /* Fill RFTx FIFO by Tx_buf[]: */
        for (uint16_t tmp = 0u; tmp < TX_SIZE; tmp++)
        {
            RfTx_FifoWriteByte(Tx_buf[tmp]);
        }
        /* Implement RFTx calibration if it's requested */
        /* For power saving the calibration should be done as close as possible to RFTx start */
        if (RFTx_Calibration == REQUEST)
        {   /* RFTx calibration is requested */
            (void)RfTx_Calibrate();
        }
        else { /* Otherwise, RFTx calibration is not needed */ }

        RfTx_Run();
        if (RFTx_Frame_Counter == 0u)
        {   /* Transmit the last frame of the message */
            Sys_DeepSleepWith(LF_RECEIVE);
        }
        else
        {   /* Transmit not the last frame of the message */
            Sys_SleepWith(LF_RECEIVE);
        }
    }

    return 0;
}   /* main */

/* ----------------------------------------------------------------------------
 * WakeupTimer_Random_Init
 * Arguments:   none
 * Returns:     none
 * Notes:
 */
STATIC void WakeupTimer_Random_Init(void)
{
    uint8_t WUP_mant;

    /* taps: 16 14 13 11; characteristic polynomial: x^16 + x^14 + x^13 + x^11 + 1 */
    rand_lfsr = (rand_lfsr >> 1) ^ ( ((-(rand_lfsr & (uint16_t)0x0001))) & (uint16_t)0xB400);   /* LDRA: negation used for optimization */
    random_base = (random_base << 1) | (rand_lfsr & (uint16_t)0x0001);
    WUP_mant = (uint8_t)(random_base & (uint16_t)0x007F) + (RFTx_MIN_RANDOM_DELAY - 1);         /* random delay in ms */
    WakeupTimer_Restart((WakeupTimerPeriod_Type){.mant = WUP_mant, .exponent = 0u});
}  /* WakeupTimer_Random_Init */

/* ----------------------------------------------------------------------------
 * Init Random generator
 * Arguments:   none
 * Returns:     none
 * Notes:
 */
INLINE STATIC void InitRandomGenerator(void)
{
uint16_t IDwordLow;

    IDwordLow = Sys_GetChipId().as_word[0];
    if (IDwordLow != 0u)
    {   /* In the scratchpad memory init a linear feedback shift register rand_lfsr */
        rand_lfsr = IDwordLow;
    }
    else
    {
        rand_lfsr = 0x0001u;
    }
    random_base = 0u;
} /* InitRandomGenerator*/

/* ----------------------------------------------------------------------------
 * Measure_PTVA
 */
STATIC void Measure_PTVA(void)
{
    Adc_RawPvt_Type raw_pvt;
    int16_t acceleration;
    uint16_t low_chipID, high_chipID;
    uint16_t tmp16;
    uint8_t tmp8;

    NvRam_Recall(); /* This function needs NVRAM content */
    /* Read Chip ID factory stored in the NVRAM, LSB first */
    low_chipID  = Sys_GetChipId().as_word[0];
    high_chipID = Sys_GetChipId().as_word[1];
    Tx_buf[3] = (uint8_t)low_chipID;
    Tx_buf[2] = (uint8_t)(low_chipID >> 8);
    Tx_buf[1] = (uint8_t)high_chipID;
    Tx_buf[0] = (uint8_t)(high_chipID >> 8);

    Adc_ReadPVT(&raw_pvt);

    #if defined (HAS_ACCEL_Z_SENSOR)
        /* Z-axis acceleration sensor is assigned in profile */
        /* for Z sensitive axis of Z / XZ accelerometer */
        #if defined (RAW_ADC_WITH_HW_FILTERING)
            Accel_InitFilterForZ(HWF_TYPE_0, 0u, 10u /* x0.1 ms */);
            acceleration = Accel_WaitAndReadNext();
            Accel_DeinitFilter();
        #else
            acceleration = Phys_AccelerationZ();
        #endif /* RAW_ADC_WITH_HW_FILTERING */

    #elif defined (HAS_ACCEL_X_SENSOR)
        /* X-axis acceleration sensor is assigned in profile */
        /* for X sensitive axis of X / XZ accelerometer */
        #if defined (RAW_ADC_WITH_HW_FILTERING)
            Accel_InitFilterForX(HWF_TYPE_0, 0u, 10u /* x0.1 ms */);
            acceleration = Accel_WaitAndReadNext();
            Accel_DeinitFilter();
        #else
            acceleration = Phys_AccelerationX();
        #endif /* RAW_ADC_WITH_HW_FILTERING */

    #else
        /* Acceleration sensor is not available (e.g. in case of MLX91803) */
        acceleration = 0u;

    #endif

    if (!Adc_IsError())     /* if no error  .. */
    {   /* Convert to physical values if no error reported: */
        /* Pressure in [kPa] equals to high word of "Calc_Pressure_32b" */
        tmp16 = (uint16_t)(Calc_Pressure(raw_pvt.pressure, raw_pvt.temperature, raw_pvt.voltage) >> 16);
        if (tmp16 < 100u)
        {
            Tx_buf[4] = 0x01u;
        }
        else if (tmp16 > 730u)
        {
            Tx_buf[4] = 0xFFu;
        }
        else
        {
            tmp16 = ((tmp16 - 100u) * (10u * 2u)) / 25u;
            if ((tmp16 & 1u) == 0u)
            {
                Tx_buf[4] = (uint8_t)(tmp16 >> 1) + 2u;
            }
            else
            {
                Tx_buf[4] = (uint8_t)(tmp16 >> 1) + 2u + 1u;
            }
        }
        /* Temperature in [degC] equals to high byte of "Calc_Temperature_16b" - 52degC */
        tmp8 = (uint8_t)(Calc_Temperature(raw_pvt.temperature) >> 8);
        if (tmp8 < 12u)                 /* 12 degC = -40 degC + 52 degC */
        {
            Tx_buf[5] = 0x01u;
            previous_temperature = 0u;
            RFTx_Calibration = REQUEST; /* Force RFTx calibration because the temperature is not well defined */
        }
        else if (tmp8 > 177u)           /* 177 degC = +125 degC + 52 degC */
        {
            Tx_buf[5] = 0xF8u;
            previous_temperature = 0u;
            RFTx_Calibration = REQUEST; /* Force RFTx calibration because the temperature is not well defined */
        }
        else
        {
            Tx_buf[5] = tmp8;
            /* Define a need of RFTx calibration */
            if (previous_temperature > tmp8)
                tmp8 = previous_temperature - tmp8;
            else
                tmp8 = tmp8 - previous_temperature;
            if ((previous_temperature == 0u) || (tmp8 > RFTX_TEMPERATURE_THRESHOLD))
            {   /* RFTx calibration is needed */
                previous_temperature = Tx_buf[5];   /* Store the temperature with a new RFTx calibration */
                RFTx_Calibration = REQUEST;         /* Force RFTx calibration because of too big temperature change */
            }
            else
            {   /* RFTx calibration is not needed */
                RFTx_Calibration = NO_REQUEST;  /* To cancel RFTx calibration */
            }
        }
        /* If RAW_ADC_WITH_HW_FILTERING is defined, "acceleration" carries result of ADC measurement */
        /* Otherwise, Acceleration in [g] equals to "acceleration" divided by 10 */
        Tx_buf[6] = (uint8_t)(acceleration >> 8);
        Tx_buf[7] = (uint8_t)acceleration;

        /* Battery voltage [V] = (float)tmp16 / 100. */
        tmp16 = Calc_Voltage(raw_pvt.voltage);
        if (tmp16 <= 150u)      /* if measured battery voltage < 1.5 V */
        {
            Tx_buf[8] = 0u;     /* too low value */
        }
        else if (tmp16 >= 405u) /* if measured battery voltage > 4.05 V */
        {
            Tx_buf[8] = 0xFFu;  /* too big value */
        }
        else    /* expected acceptable voltage range: 1.5...4.05V, saturation is not processed */
        {       /* Battery voltage in [V] equals to "Tx_buf[7]"/100 plus 1.5V */
            Tx_buf[8] = (uint8_t)(tmp16 - 150u);
        }
    }
    else
    {   /* .. error handler */
        Adc_ClearAllErrors();      /* Clear all possible ADC errors */
        Tx_buf[4] = DUMMY_CODE;
        Tx_buf[5] = DUMMY_CODE;
        Tx_buf[6] = DUMMY_CODE;
        Tx_buf[7] = DUMMY_CODE;
        Tx_buf[8] = DUMMY_CODE;
        previous_temperature = 0u;
        RFTx_Calibration = REQUEST;
    }
}   /* Measure_PTVA */

/* ----------------------------------------------------------------------------
 * LF command parsing
 * Arguments:   None
 * Returns:     None
 * Notes:
 */

/* Expected LF command: WakeUp_ID {0x8F, 0x61}, Data {0x01, 0x02, 0x03, 0x04, STT} */
#define LFRX_PAYLOAD_SIZE   (5u)
STATIC const uint8_t LF_command_fixed_part[LFRX_PAYLOAD_SIZE-1u] = {0x01u, 0x02u, 0x03u, 0x04u};

STATIC INLINE void Process_LF_Message(void)
{
    uint8_t  tmp8;
    uint16_t i;

    tmp8 = LfRx_FifoCount();
    if (tmp8 >= LFRX_PAYLOAD_SIZE)
    {
        for (i = 0u; i < (LFRX_PAYLOAD_SIZE-1u); i++)
        {
            tmp8 = LfRx_FifoReadByte();
            if (LF_command_fixed_part[i] != tmp8)
                break;
        }
        if (i == (LFRX_PAYLOAD_SIZE-1u))
        {   /* array LF_command_fixed_part[] matches the received data */
            tmp8 = LfRx_FifoReadByte();     /* Take received STT value */
            if (tmp8 == 0u)                 /* and execute LF command */
            {   /* Set zero STT_id and forbid reporting */
                STT_id = 0u;
                RFTx_Frame_Counter = 0u;
                WakeupTimer_Init(WUT_MANT[0], WUT_EXP[0]);
            }
            else if ((tmp8 & 0x0Fu) == (tmp8 >> 4))
            {   /* Redefine STT_id by the new received value */
                WakeupTimer_Restart(TRANSFER_DELAY);
                STT_id = tmp8 & 0x0Fu;
            }
            else if (tmp8 == RESET_CODE)
            {   /* Initialize software reset after some delay */
	            reset_cmd = RESET_CODE;
	            Wakeup_Disable(WAKEUP_LF_DONE);
	            WakeupTimer_Restart(RESET_DELAY);
	            Sys_DeepSleepWith(LF_DISABLED);
            }
            else {  /* Else: just ignore the received data, because it's neither equal to RESET_CODE */
                    /* nor two nibbles of the received STT byte match each other */ }
        }
        else {      /* Else: just ignore the received data, */
                    /* because it doesn't match LF_command_fixed_part[] */ }
    }
    else {          /* Else: received data size is too small */ }
    LfRx_FifoFlush();
}  /* Process_LF_Message */

/* ----------------------------------------------------------------------------
 * RFTx configuration
 * Arguments:   none
 * Returns:     none
 * Notes:
 */

STATIC INLINE void InitRFTx(void)
{
STATIC const RfTxConfig_Type cfg_rf =
    {{  /* Note: All unconfigured fields keeps their default zero values */
        .RFTX_PATTERN_LEN = 1,      /* 2 bits a length of the synchronization pattern : 0 = 8 bits, 1 = 16 bits, 2 = 24 bits, 3 = 32 bits */
        .RFTX_MULTI_FRAME = 0,      /* 1 bit, not used (Enable the transmission of packets consisting of multiple frames) */
/* 3-bit of modulation source selection:
0 = Fixed logic 0, 1 = All raw data from FIFO, no preamble, sync pattern or packet
2 = Preamble and sync pattern, no packet, 3 = Preamble, sync pattern and packet,
4 = GPIO0 input, 5 = GPIO1 input, 6 = GPIO2 input, 7 = GPIO3 input */
        .RFTX_DIRECT_MOD = 3,
        .RF_EN_PD = 0,              /* 1 bit to enable RF TX power detector (if it's 1) */

/* Time to wait before declaring PLL in-lock (2-bits): 0 = 40 us, 1 = 80 us, 2 and 3 = reserved */
        .RFTX_WAIT_LOCK = 1,

        .RFTX_PREAMBLE = 0xAA,      /* 8-bit preamble pattern */
        .RFTX_PREAMBLE_LEN = 1,     /* 8-bit that defines a length of the preamble to be transmitted (number+1 of RFTX_PREAMBLE bytes in NRZ) */

        .RFTX_PATTERN_L = 0xAAA9,   /* Low  word of 32-bit RF TX synchronization word (in NRZ) */
        .RFTX_PATTERN_H = 0x0000,   /* High word of 32-bit RF TX synchronization word */
        .RFTX_PACKET_LEN = TX_SIZE, /* 8-bit packet length in fixed packet length mode */
        .RFTX_PACKET_LEN_CORR = 0,  /* 4-bit signed word that specifies how the packet length should be corrected */
/* 2-bit position of the packet length byte, starting from the synchronization word (only applicable when the packet length is not fixed) */
        .RFTX_PACKET_LEN_POS = 0,
        .RFTX_PACKET_LEN_FIX = 1,   /* Packet length: 0 = variable, 1 = fixed */

        .RFTX_ADDRESS = 0x00,       /* 8-bit address to be transmitted when address byte is enabled */
        .RFTX_EN_ADDRESS = 0,       /* Add address byte to transmitted packets */

        .RFTX_CRC_INV = 0,          /* Optional inversion of the CRC value */
        .RFTX_CRC_16_N8 = 0,        /* CRC length and type: 0 = 8 bit, Baicheva polynomial, 1 = 16 bit, CCITT */
        .RFTX_EN_CRC = 1,           /* Add CRC to transmitted packets */
        .RFTX_CRC_INIT = 0xAA00,    /* 16-bit initial value for CRC calculation. In case of 8-bit CRC, the init value is in RFTX_CRC_INIT[15:8] */

/* Baud rate = Crystal frequency / ((240 + RFTX_DR_MANT) * 2^(RFTX_DR_EXP-1)), half of this for Manchester encoding */
        .RFTX_DR_MANT = 0x63,       /* 8-bit mantissa seting 19174 baud rate to approach 9600 bps with 26 MHz crystal */
        .RFTX_DR_EXP = 0x03,        /* 3-bit exponent seting 19174 baud rate to approach 9600 bps with 26 MHz crystal */

        .RFTX_LSB_FIRST = 0,        /* Select the bit order: 0 = MSB first, 1 = LSB first */
        .RFTX_EN_MANCHESTER = 1,    /* Enable Manchester coding of the data bits: 0 = NRZ, 1 = Manchester */
/* TX ramp up/down duration: 0 = no ramp up/down, 1 = 40us, 2 = 80us, 3 = 160us, 4 = 320us, 5 = 640us, 6 = 1.3ms, 7 = 2.6ms */
        .RFTX_RAMP = 0,

        .RFTX_MANCHESTER_STOP_WORD = 0x00,  /* 8-bit stop word for Manchester encoding */
/* 2-bit length of stop word in case of Manchester encoding: 0 = 0 bit, i.e. no stop word, 1 = 2 bits, 2 = 4 bits, 3 = 8 bits */
        .RFTX_MANCHESTER_STOP_LEN = 0,

/* 4-bit values RFTX_MULT_MANT and RFTX_MULT_EXP define FSK frequency deviation */
        .RFTX_MULT_MANT = 8,
        .RFTX_MULT_EXP = 2,
/* Invert the polarity of the data bits if set. In case of Manchester encoding: 1 = direct, 0 = inverse */
        .RFTX_BIT_INVERT = 1,
        .RFTX_PN9_MODE = 0,         /* Select TI-compatible PN9 sequence */
        .RFTX_PN9_REVERSE = 0,      /* Generate PN9 sequence: 0 = LSB first, 1 = MSB first (TI-compatible) */
        .RFTX_EN_DATAWHITE = 0,     /* Enable data whitening (if it's = 1) */
/* Interpolator on TX modulator output: 0 = OFF; 1 = ON, at 13 MHz; 2 = ON, at 6.5 MHz; 3 = ON, at 3.25 MHz */
        .RFTX_EN_INTERP = 0,
        .RFTX_EN_GAUSSIAN = 0,      /* Enable Guassian pulse shaping */
        .RFTX_FSK_NOOK = 1,         /* Select the modulation type: 0 = OOK, 1 = FSK */
    }};

    RfTx_Init(&cfg_rf);             /* Apply parameters specified in the "cfg_rf" */
} /* InitRFTx */

/* ----------------------------------------------------------------------------
 * IO ports configuration
 * Arguments:   none
 * Returns:     none
 * Notes:
 */
STATIC INLINE void InitIOports(void)
{
    STATIC const GpioConfig_Type cfg_io =
    {{
        .GPIO0_DRV = 2,                 /* Output driving strength settings */
        .GPIO1_DRV = 2,                 /* Available levels:  0, 1, 2 and 3 */
        .GPIO2_DRV = 2,
        .GPIO3_DRV = 2,
        /* GPIOs initial states: */
        .GPIO0_CH_SEL = GPIO_DISABLED,
        .GPIO1_CH_SEL = GPIO_DISABLED,
        .GPIO2_CH_SEL = GPIO_DISABLED,
        .GPIO3_CH_SEL = GPIO_DISABLED   /* Note: GPIO3 is not available */
    }};
    Gpio_Init(&cfg_io);
} /* InitIOports */

/* ----------------------------------------------------------------------------
 * LFRx configuration
 * Arguments:   none
 * Returns:     none
 * Notes:
 */
INLINE STATIC void InitLFRx(void)
{
    STATIC const LfConfig_Type cfg_lf =
    {{
/* TX config */
    .LFTX_MODE  = LFTX_MANCHESTER_LSB_FIRST,    /* 3 bits defining the LFTx modulation source */
    .LFTX_POL   = LFTX_POLARITY_1,              /* LFTx polarity */

/* RX config */
    /* LFRx control */
    .LF_EN_FD       = 0,        /* 1 bit: being set it enables LFRX fault detection mechanism */
    .LFRX_STBY_ON   = 0,        /* 1 bit: being set it keeps LF analog interface enabled during standby phase of RX polling */
    /* LFRX standby interval (single shot if LFRX_STBY_MANT = 0 and LFRX_STBY_EXP = 0 */
    /* If LFRX_STBY_EXP = 0, Standby interval [ms] =  LFRX_STBY_MANT */
    /* If LFRX_STBY_EXP > 0, Standby interval [ms] = (LFRX_STBY_MANT+16) * 2^(LFRX_STBY_EXP-1) */
    .LFRX_STBY_EXP  = 8,        /* 4-bit exponent of the Standby interval */
    .LFRX_STBY_MANT = 0,        /* 4-bit mantissa of the Standby interval */
    /* Timeout interval limiting preamble detection duration (no timeout, if both mantissa and exponent are zero */
    /* If LFRX_TIMEOUT_EXP = 0, Timeout [ms] =  LFRX_TIMEOUT_MANT */
    /* If LFRX_TIMEOUT_EXP > 0, Timeout [ms] = (LFRX_TIMEOUT_MANT+16) * 2^(LFRX_TIMEOUT_EXP-1) */
    .LFRX_TIMEOUT_EXP   = 2,    /* 4-bit exponent of the timeout interval */
    .LFRX_TIMEOUT_MANT  = 15,   /* 4-bit mantissa of the timeout interval */
    .LF_GAIN_SEL    = LF_GAIN_MAX,  /* Gain setting for LF analog front-end: LF_GAIN_MAX or LF_GAIN_MIN */

    /* Manchester parameters */
    .LFRX_ORDER     = LFRX_ORDER_MSB_FIRST, /* LF RX bit order inside of any byte: 0 = LSB first, 1 = MSB first */
    .LFRX_POL       = 0,        /* LFRx polarity: if it's zero -> high-to-low corresponds to Manchester's "0" */

    /* Preamble validation */
    .LFRX_PREAMBLE  = 1,        /* 1 bit to enable preamble validation: "1" to enable, "0" to disable */
    .LFRX_LONGCNT   = 1,        /* 1 bit specifying a number of 32 kHz periods to validate preamble: "0" - 5 cycles, "1" - 10 cycles */
    .LFRX_MINCNT    = 22,       /* 6-bit minimum counter value for valid preamble */
    .LFRX_DELTACNT  = 20,       /* 6-bit (maximum - minimum) counter value for valid preamble */

    /* Sync word */
    .LFRX_SYNCLEN       = 9,    /* 4-bit LF RX synchronization word length, up to 16 SYNC DIGITs */
    .LFRX_SYNCPOL       = 1,    /* Synchronization pattern starts with falling (0) or rising (1) edge */
    /* 2-bits durations of LFRX synchronization pattern's digits (in Tsymbols): 0 = 0.5, 1 = 1, 2 = 1.5, 3 = 2 */
    .LFRX_SYNC_DIGIT1   = 0,    /* last     digit  duration, default value = 0 */
    .LFRX_SYNC_DIGIT2   = 1,    /* last - 1 digit  duration, default value = 1 */
    .LFRX_SYNC_DIGIT3   = 1,    /* last - 2 digit  duration, default value = 1 */
    .LFRX_SYNC_DIGIT4   = 1,    /* last - 3 digit  duration, default value = 1 */
    .LFRX_SYNC_DIGIT5   = 1,    /* last - 4 digit  duration, default value = 1 */
    .LFRX_SYNC_DIGIT6   = 0,    /* last - 5 digit  duration, default value = 0 */
    .LFRX_SYNC_DIGIT7   = 0,    /* last - 6 digit  duration, default value = 0 */
    .LFRX_SYNC_DIGIT8   = 2,    /* last - 7 digit  duration, default value = 2 */
    .LFRX_SYNC_DIGIT9   = 2,    /* last - 8 digit  duration, default value = 2 */
    .LFRX_SYNC_DIGIT10  = 0,    /* last - 9 digit  duration, default value = 0 */
    .LFRX_SYNC_DIGIT11  = 0,    /* last - 10 digit duration, default value = 0 */
    .LFRX_SYNC_DIGIT12  = 0,    /* last - 11 digit duration, default value = 0 */
    .LFRX_SYNC_DIGIT13  = 0,    /* last - 12 digit duration, default value = 0 */
    .LFRX_SYNC_DIGIT14  = 0,    /* last - 13 digit duration, default value = 0 */
    .LFRX_SYNC_DIGIT15  = 0,    /* last - 14 digit duration, default value = 0 */

    /* Header */
    .LFRX_HDRLEN    = LFRX_HDR_16_BITS, /* LF RX header length: "0" - no header, "1" - 1 byte, "2" - 2 bytes, "3" - 4 bytes of header */
    .LFRX_HDR_L     = 0x618F,           /* Lowest  16-bit header to be recognized in LFRx with LFRX_HDRLEN = LFRX_HDR_16_BITS */
    .LFRX_HDR_H     = 0x618F,           /* Highest 16-bit header to be recognized in LFRx with LFRX_HDRLEN = LFRX_HDR_16_BITS */
    /* 32-bit mask for header to be recognized in LF RX. Each bit of the mask means: "0" - don't care, "1" - to be matched */
    .LFRX_HDR_MASK_L    = 0xFFFF,       /* The mask for the lowest  16-bit header for LFRX_HDRLEN = LFRX_HDR_16_BITS */
    .LFRX_HDR_MASK_H    = 0xFFFF        /* The mask for the highest 16-bit header for LFRX_HDRLEN = LFRX_HDR_16_BITS */
    }};

    Lf_Init(&cfg_lf);

    Wakeup_Enable(WAKEUP_LF_DONE);
} /* InitLFRx */

/* EOF */
