/*
 * Copyright (C) 2016-2022 Melexis N.V.
 *
 * Software Platform
 */

/*
 * LFO performance evaluation
 *
 * After the Cold boot the example configures:
 * GPIO0 to monitor 1 kHz clock applied to the Wake-Up Timer
 * GPIO1 to choose either LFO calibration if "1", or the MLX factory trimming if "0"
 * GPIO2 to control the LFO mode ("1" sets NORMAL, "0" or floating state sets ULP mode of LFO)
 * The example provides a scenario with wake-ups generated by the changes of GPIO1/2 state
 * Any new state provokes one of 4 possible LFO configuration:
 * GPIO1=0, GPIO2=0 => MLX factory trimming in ULP mode of LFO
 * GPIO1=0, GPIO2=1 => MLX factory trimming in NORMAL mode of LFO
 * GPIO1=1, GPIO2=0 => LFO calibration in ULP mode of LFO
 * GPIO1=1, GPIO2=1 => LFO calibration in NORMAL mode of LFO
 */
 
#include <delay.h>
#include <sensorlib.h>

//#define USE_EXTERNAL_REFERENCE_CLOCK

//#define RESTORE_ALL

#define gpio12_mask_00  ((0u << (uint8_t)GPIO1) | (0u << (uint8_t)GPIO2))
#define gpio12_mask_01  ((0u << (uint8_t)GPIO1) | (1u << (uint8_t)GPIO2))
#define gpio12_mask_10  ((1u << (uint8_t)GPIO1) | (0u << (uint8_t)GPIO2))
#define gpio12_mask_11  ((1u << (uint8_t)GPIO1) | (1u << (uint8_t)GPIO2))

#define MIN_NUMBER  (8u)

STATIC SP_MEM uint8_t previous_gpio12_state;

/*
 * Main
 */
int main (void)
{
    uint8_t gpio12_state;
    uint16_t anti_bounce;

    if (Sys_IsColdBoot()) {
        /* Wakeups from WUT are not needed - keep them at maximal value that is 
        set by default at cold boot:
        WakeupTimer_Restart(WT_PERIOD_MAX); */
        /* Assign GPIO0 to out 1 kHz LFO clock when sleeping: */
        Gpio_SetPinMode(GPIO0, GPIO_1_KHZ_CLOCK);
        /* Assign GPIO1 to be input switching between calibration and trimming: */
        Gpio_SetPinMode(GPIO1, GPIO_DIG_INPUT_WITH_PULLDOWN);
        /* Assign GPIO2 to be input switching between NORMAL and ULP modes of LFO: */
        Gpio_SetPinMode(GPIO2, GPIO_DIG_INPUT_WITH_PULLDOWN);
        /* GPIO1 and GPIO2 are presumed floating at the beginning */
        previous_gpio12_state = gpio12_mask_00;
        /* Otherwise the wakeup will be generated immediately: */
        Wakeup_Enable(WAKEUP_GPIO1_HIGH);
        Wakeup_Enable(WAKEUP_GPIO2_HIGH);
    }
    else if (Itc_IsPending(ITC_WUPTMR)) {   /* wake-up from WUT */
        /* Just clean the wake-up source from the WUT, no other actions are needed */
        WakeupTimer_IntClear(); 
    }
    else {                                  /* wake-up from GPIO1 or GPIO2 */
        delay_nops(20000u); /* Delay about 10 ms @ 8 MHz to skip the time when MuPET uses GPIO2 */

        gpio12_state = (uint8_t)Gpio_ReadPort() & gpio12_mask_11;

        if (previous_gpio12_state != gpio12_state) {
        
            previous_gpio12_state = gpio12_state;       /* refresh the state */
    
            switch((uint8_t)gpio12_state) {             /* Verify input state of GPIO1 and GPIO2 */
                /* GPIO1=0, GPIO2=0 => MLX factory trimming in ULP mode of LFO */
                case gpio12_mask_00:
                    NvRam_Recall();                     /* Recall the nvRAM to have a valid data on its RAM layer */
                    #if defined (RESTORE_ALL)
                    /* Restore all factory calibration parameters for both HFO and LFO */
                    NvRam_RestoreOscTrimming();
                    #else
                    NvRam_RestoreUlpoTrimming();        /* use the MLX factory trimming for 1 kHz RC-oscillator */
                    #endif /* RESTORE_ALL */
                    Sys_SetUlpLfo();                    /* with ULP LFO mode */
                    Wakeup_Enable(WAKEUP_GPIO1_HIGH);   /* Prepare a condition for the next wakeup */
                    Wakeup_Enable(WAKEUP_GPIO2_HIGH);
                    break;
                /* GPIO1=0, GPIO2=1 => MLX factory trimming in NORMAL mode of LFO */
                case gpio12_mask_01:
                    NvRam_Recall();                     /* Recall the nvRAM to have a valid data on its RAM layer */
                    #if defined (RESTORE_ALL)
                    /* Restore all factory calibration parameters for both HFO and LFO */
                    NvRam_RestoreOscTrimming();
                    #else
                    NvRam_RestoreLfoTrimming();         /* use the MLX factory trimming for 32 kHz RC-oscillator */
                    #endif /* RESTORE_ALL */
                    Sys_SetNormalLfo();                 /* with NORMAL LFO mode */
                    Wakeup_Enable(WAKEUP_GPIO1_HIGH);   /* Prepare a condition for the next wakeup */
                    Wakeup_Enable(WAKEUP_GPIO2_LOW);
                    break;
                /* GPIO1=1, GPIO2=0 => LFO calibration in ULP mode of LFO */
                case gpio12_mask_10:
                    #if defined (USE_EXTERNAL_REFERENCE_CLOCK)
                    (void)Sys_CalibrateUlpoByExtClk();  /* Calibrate 1 kHz RC-generator with External 8MHz reference */
                    #else
                    (void)Sys_CalibrateUlpo();          /* Calibrate 1 kHz RC-generator with XTAL reference */
                    #endif /* USE_EXTERNAL_REFERENCE_CLOCK */
                    Sys_SetUlpLfo();                    /* and switch to the ULP LFO mode */
                    Wakeup_Enable(WAKEUP_GPIO1_LOW);    /* Prepare a condition for the next wakeup */
                    Wakeup_Enable(WAKEUP_GPIO2_HIGH);
                    break;
                /* GPIO1=1, GPIO2=1 => LFO calibration in NORMAL mode of LFO */
                default:
                    #if defined (USE_EXTERNAL_REFERENCE_CLOCK)
                    (void)Sys_CalibrateLfoByExtClk();   /* Calibrate 32 kHz RC-generator with External 8MHz reference */
                    #else
                    (void)Sys_CalibrateLfo();           /* Calibrate 32 kHz RC-generator with XTAL reference */
                    #endif /* USE_EXTERNAL_REFERENCE_CLOCK */
                    Sys_SetNormalLfo();                 /* and switch to the NORMAL LFO mode */
                    Wakeup_Enable(WAKEUP_GPIO1_LOW);    /* Prepare a condition for the next wakeup */
                    Wakeup_Enable(WAKEUP_GPIO2_LOW);
                    break;
            }
        }
        else { /* just keep the state set before */ }

        anti_bounce = 0u;

        while (anti_bounce < MIN_NUMBER) {
            if (gpio12_state == ((uint8_t)Gpio_ReadPort() & gpio12_mask_11)) {
                anti_bounce++;
            }
            else {
                gpio12_state = (uint8_t)Gpio_ReadPort() & gpio12_mask_11;
                anti_bounce = 0u;
            }
            delay_nops(10000u); /* Delay about 5 ms @ 8 MHz */
        }
    }

    Sys_DeepSleepWith(LF_DISABLED);

    return 0;
}

/* EOF */
