# -*- coding: utf-8 -*-
"""
@hex_to_array_converter.py
@copyright (C) Melexis N.V.

THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
"""

import time
import os

timestr = time.strftime("%B %d, %Y at %H:%M:%S")
file_name = "output\mlx_memory_image.c"

#Melexis .hex file absolute path or name
#myHexfile = r'C:\Projects\Git\onsemi\tpms_ble_demo_fota\MLX91805_tpms_ble_demo_fota\MLX91805_tpms_ble_demo_fota.hex'
#myHexfile = r'C:\Share\ICdata\Melexis\20220810\MLX91805_TPMS_BLE_Demo_Fota\MLX91805_TPMS_BLE_Demo_Fota\MLX91805_tpms_ble_demo_fota\MLX91805_tpms_ble_demo_fota.hex'
myHexfile = r'BSIxx-SGA_mems.hex'

f= open(file_name,"w+") #create or open the file 

intro = "\
/***************************************************************************//**\n\
 * file "+file_name+"\n\
 * Melexis memory images for Flash and nvRAM\n\
 * Automatically generated by Python script on "+ timestr +"\n\
 * copyright (C) Melexis N.V.\n\
 *\n\
 *\n\
 * THIS SOFTWARE IS PROVIDED \"AS IS\".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,\n\
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n\
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,\n\
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.\n\
*******************************************************************************/\n\
#include \"mlx_memory_image.h\"\n\
\n\
const uint16_t mlx_nvram_hex[NVRAM_DATA_LENGHT] = {\n\
    0x0001,0x0003,0x0005,0x0007,0x0009,0x000B,0x000D,0x000F,\n\
    0x0011,0x0013,0x0015,0x0017,0x0019,0x001B,0x001D,0x001F,\n\
    0x0021,0x0023,0x0025,0x0027,0x0029,0x002B,0x002D,0x002F,\n\
    0x0031,0x0033,0x0035,0x0037,0x0039,0x003B,0x003D,0x003F\n\
};\n\
\n\
/* "+ os.path.basename(myHexfile) +" */\n\
const uint16_t mlx_flash_hex [ROWS][COLUMNS] = {" 

print ( intro ) 
f.write(intro + "\n" ) 

print ("\n\n...\n\n")                                    #just for fun 

with open(myHexfile) as fhex:
    
    lines = fhex.readlines()                              #read all lines    
    for line in lines:                                    #for each lines 
        line_to_list = list(line.strip())                 #convert line to list 
        byte_count= str(line[1]+ line[2])                 #extract .hex Byte count
        byte_count_uint = int( byte_count,16)             #convert Byte count to uint16
        start = 9                                         #filter out .hex Start code, Byte count, Address and Record type
        stop = (len(line_to_list)-2)                      #filter out .hex Checksum
        data = line[start:stop]                           #extract the .hex data 
        extracted_data = list(range(0, int(len(data)/4))) #create array 2 times smaller than reduced list 
        if byte_count_uint != 00:                         #check if there is data 
            f.write("    {")
            for i  in range(0, len(extracted_data) ,1):   #write the data
                extracted_data [i] = "0x"   + str(data [i*4+2]) + str(data [i*4+3]) + str(data [i*4]) + str(data [i*4+1])
                f.write(extracted_data[i])
                if (i < len(extracted_data)-1): 
                    f.write(",")
            if (byte_count_uint == 16):                   #if extracted data = max lengh (16)
                f.write("},\n")                           #EOL
            else:                                         #if the extracted data < max lengh (16)  
                for y in range (0, (int(16/2)-len(extracted_data)),1): #max lengh (16) - extracted data.
                        f.write(",0x0000")                #fill by 0 to reach max lengh (16) 
                f.write("},\n")                           #EOL
       # else:                                             #if there is no data: ignore 
          # f.write("    //"+line)
            
    if (len(lines)!=1025):                                #fill the rest of the table by 0
        for i in range (len(lines), 1025):
            f.write("    {0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000},\n")
#EOF                
print ("};\n\n/* EOF */")
f.write("};\n\n/* EOF */\n")

#close
f.close()
fhex.close()

